on:
  push:
    branches:
      - main
      - login-gcr.io 

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'homework3-440622' 
          workload_identity_provider: 'projects/1086037284239/locations/global/workloadIdentityPools/github/providers/my-repo' 
      - name: Configure Docker to use gcloud
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: us-central1-docker.pkg.dev/homework3-440622/docker-repo/my-image:latest
